runtime! debian.vim
set shell=/bin/bash
filetype plugin indent on    " required

syntax on
set background=dark

" Load commands / settings by filetype
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
" set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" PERSONAL CUSTOMIZATIONS
set hlsearch
set backspace=indent,start
set autoindent
set ruler
set number
set relativenumber
set pastetoggle=<F11>
set shiftwidth=4
set softtabstop=4
set expandtab
set wildmenu
set lazyredraw
set backspace=2
set noshowmode
set spell spelllang=en

" Markdown settings
let g:markdown_fenced_languages = ['java', 'c', 'bash=sh', 'python']

" Visual Line movements
noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
noremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')

" B goes to the start of the line
nnoremap B ^
" E goes to the end
nnoremap E $
" ?
nnoremap gV '[v']
let mapleader=","

" Make backups less awful
set nobackup
" set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
" set backupskip=/tmp/*,/private/tmp/*
" set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
" set writebackup

" Always show statusline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256
" colours)
set t_Co=256
set term=screen-256color
set nomodeline

